## **Agata Semerjak, 402426**  
gr 1a, środa 14:45  
**lab 9** 5.05.2021

**Zadanie 1.**  
  
Algorytm Johnsona dla problemu 2 maszyn.

In [1]:
import numpy as np

def Johnosn_2machines(m):
    m = m.astype(float)
    last_idx = m.shape[1] - 1
    size = last_idx + 1
    new_order = np.array([[None for _ in range(size)], [None for _ in range(size)]]) #pusta macierz czasów
    new_tasks = [None for _ in range(size)] #tablica nowej kolejnosci zadan
    for _ in range(size):
        i, j = np.unravel_index(np.nanargmin(m, axis=None), m.shape) #indeksy najmniejszego elementu
        if i == 0: #jeśli leży w 1 wierszu
            idx = 0
            while new_order[0, idx] is not None:
                idx += 1 #ustawienie indeksu na pierwsze wolne miejsce od lewej
        elif i == 1:
            idx = last_idx
            while new_order[0, idx] is not None:
                idx -= 1 #ustawienie indeksu na pierwsze wolne miejsce od końca

        new_order[0, idx] = m[0, j] #wstawienie danych z wejściowej macirzy czasów do wynikowej
        new_order[1, idx] = m[1, j]
        new_tasks[idx] = j+1 #uzupełnienie kolejności zadań

        m[0, j] = np.NaN #wykreślenie z macierzy wejściowej kolumny, w której znajdował się element minimalny
        m[1, j] = np.NaN

    time = new_order.copy().astype(int) #macierz terminów
    temp = 0
    for i in range(time.shape[1]):
        time[0, i] += temp #uzupełnienie pierwszego wiersza (tj czas poprzednika + czas)
        temp = time[0, i]

    left = 0
    for i in range(time.shape[1]): #uzupełnienie drugiego wiersza (tj max(ponad, po lewej) + czas)
        up = time[0, i] #czas elementu ponad
        if left > up:
            time[1, i] += left #jeśli element po lewej jest większy to jego dodajemy do czasu
        else:
            time[1, i] += up #jeśli element ponad jest większy to jego dodajemy do czasu
        left = time[1, i] #czas elementu po lewej

    return new_order.astype(int), time, new_tasks

Przykład działania dla macierzy z konspektu:

In [4]:
m = np.array([[9, 6, 8, 7, 12, 3], [7, 3, 5, 10, 4, 7]])
def print_john(m):
    print("Macierz wejściowa:")
    print(m)
    uszeregowanie, terminy, kolejnosc = Johnosn_2machines(m)
    print("\nUszeregowanie:\n", uszeregowanie)
    print("\nTerminy:\n", terminy)
    print("\nNowa kolejność zadań:", kolejnosc)

print_john(m)

Macierz wejściowa:
[[ 9  6  8  7 12  3]
 [ 7  3  5 10  4  7]]

Uszeregowanie:
 [[ 3  7  9  8 12  6]
 [ 7 10  7  5  4  3]]

Terminy:
 [[ 3 10 19 27 39 45]
 [10 20 27 32 43 48]]

Nowa kolejność zadań: [6, 4, 1, 3, 5, 2]


**Zadanie 2.**
  
Działanie algorytmu dla macierzy czasów dla 10 zadań.

In [6]:
m = np.random.randint(3, 15, size=(2, 10))
print_john(m)

Macierz wejściowa:
[[ 4  3  5 10  7  7 10  9 10  9]
 [ 5  6  5 11  8  7 11  6  3  3]]

Uszeregowanie:
 [[ 3  4  5  7  7 10 10  9  9 10]
 [ 6  5  5  8  7 11 11  6  3  3]]

Terminy:
 [[ 3  7 12 19 26 36 46 55 64 74]
 [ 9 14 19 27 34 47 58 64 67 77]]

Nowa kolejność zadań: [2, 1, 3, 5, 6, 4, 7, 8, 10, 9]


**Zadanie 3**
  
Rozwiązywany typ problemu to F | t_jkl | C_max.  
Alternatywne sposoby szeregowania powinny dać ten sam czas końcowy.  
Założenia dla algorytmu:
- dana maszyna może wykonywać maksymalnie jedno zadanie na raz  
- operacja nie może być przerwana
  
Złożoność obliczniowa algorytmu to O(n^2).
